name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run build and code quality checks
        run: npx nx run-many -t lint test build --parallel=3
